### ISSUE TITLE
Site is Down

### ISSUE THREAD

**Issue by Olusamimaths** [bahdcoder/testingreact.dev#2]
@bahdcoder the website, https://testingreact.dev/, is down and not accessible at the moment.
Can you check that out.

Thanks for the good work by the way.

**Comment by bahdcoder** [comment]
Hello @Olusamimaths the website for the course is https://testingreact.katifrantz.com . Will change it on the repository too. So sorry for this confusion. I earlier planned to purchase the domain but didn't. Thanks for notifying me !

**Comment by Olusamimaths** [comment]
Ok boss.
